# Generated by Django 5.0.1 on 2024-01-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Class', models.PositiveIntegerField(default=1, max_length=2)),
                ('RollNo', models.PositiveIntegerField(default=1, max_length=3)),
                ('Address', models.CharField(max_length=500)),
                ('PhoneNo', models.PositiveIntegerField(max_length=10)),
            ],
        ),
    ]
