# Generated by Django 5.0.1 on 2024-01-23 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='DOB',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='Class',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='PhoneNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='RollNo',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
