# Generated by Django 5.0.1 on 2024-01-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='DOB',
            field=models.CharField(max_length=12),
        ),
    ]
